// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5LuTK78TjxUD033C9KexzOvZg92IFhDU',
    appId: '1:497912757265:web:45df11a9d24f32149545b0',
    messagingSenderId: '497912757265',
    projectId: 'fir-project-7253a',
    authDomain: 'fir-project-7253a.firebaseapp.com',
    storageBucket: 'fir-project-7253a.firebasestorage.app',
    measurementId: 'G-2R6W4GYTJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3nTdx-Kbw7BUxNY5qWhJmh3vRY0pqArw',
    appId: '1:497912757265:android:cb369941d27a5e769545b0',
    messagingSenderId: '497912757265',
    projectId: 'fir-project-7253a',
    storageBucket: 'fir-project-7253a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaQHcmn-ZzUk6YBlgU1knDwfk7fkj7U64',
    appId: '1:497912757265:ios:310ad27696148c329545b0',
    messagingSenderId: '497912757265',
    projectId: 'fir-project-7253a',
    storageBucket: 'fir-project-7253a.firebasestorage.app',
    iosBundleId: 'com.example.loginRegpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaQHcmn-ZzUk6YBlgU1knDwfk7fkj7U64',
    appId: '1:497912757265:ios:310ad27696148c329545b0',
    messagingSenderId: '497912757265',
    projectId: 'fir-project-7253a',
    storageBucket: 'fir-project-7253a.firebasestorage.app',
    iosBundleId: 'com.example.loginRegpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5LuTK78TjxUD033C9KexzOvZg92IFhDU',
    appId: '1:497912757265:web:f2d29bbdeb616b5a9545b0',
    messagingSenderId: '497912757265',
    projectId: 'fir-project-7253a',
    authDomain: 'fir-project-7253a.firebaseapp.com',
    storageBucket: 'fir-project-7253a.firebasestorage.app',
    measurementId: 'G-2F2KTBNC9P',
  );
}
