// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2MA39gD3dWovxJbSO2mhbCspjD0XN_bI',
    appId: '1:1085954467163:web:00b2ca8843dc80fb53a67e',
    messagingSenderId: '1085954467163',
    projectId: 'gp-depi',
    authDomain: 'gp-depi.firebaseapp.com',
    storageBucket: 'gp-depi.firebasestorage.app',
    measurementId: 'G-FBPJYV3WCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDDA9RAxuW_ewWS80qVwjZppZ2jRbPMxw',
    appId: '1:1085954467163:android:77ae124ff1e2dd3a53a67e',
    messagingSenderId: '1085954467163',
    projectId: 'gp-depi',
    storageBucket: 'gp-depi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeXSuaaUC1lnTVjcpZvlJXbPcso9SBUbE',
    appId: '1:1085954467163:ios:4c119bfe5d9dca3853a67e',
    messagingSenderId: '1085954467163',
    projectId: 'gp-depi',
    storageBucket: 'gp-depi.firebasestorage.app',
    iosClientId: '1085954467163-cuh4fnn4ggh0vs1i9sfhim3tf4mnd2tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.rwadProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeXSuaaUC1lnTVjcpZvlJXbPcso9SBUbE',
    appId: '1:1085954467163:ios:82c8c644bda7eee553a67e',
    messagingSenderId: '1085954467163',
    projectId: 'gp-depi',
    storageBucket: 'gp-depi.firebasestorage.app',
    iosClientId: '1085954467163-6kvtdskd6ih43r7ojqh0langqtlvhsvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2MA39gD3dWovxJbSO2mhbCspjD0XN_bI',
    appId: '1:1085954467163:web:00b2ca8843dc80fb53a67e',
    messagingSenderId: '1085954467163',
    projectId: 'gp-depi',
    authDomain: 'gp-depi.firebaseapp.com',
    storageBucket: 'gp-depi.firebasestorage.app',
    measurementId: 'G-FBPJYV3WCY',
  );
}
